### PR TITLE
Improve design

### LINKED ISSUE #3: Styling the project
The project at the moment has minimum styling. So anyone can contribute by theming the project.

### PR DESCRIPTION
**Pull request by Ayshhh**
Resolve #3 
* Changed background 
* Styled heading

### CODE REVIEW

**Comment by BreadGenie** [comment]
Hey @Ayshhh ! Thanks for contributing can I get a screenshot of the design to see how it looks like?

**Comment by Ayshhh** [comment]
> Hey @Ayshhh ! Thanks for contributing can I get a screenshot of the design to see how it looks like?

Yeah sure @BreadGenie. I've attached screenshot of how the webpage looks :)
Screenshot (274)

**Comment by BreadGenie** [comment]
@Ayshhh the ui looks good can you also look into the encoded image sizing?

**Comment by Ayshhh** [comment]
> @Ayshhh the ui looks good can you also look into the encoded image sizing?

@BreadGenie Thanks! The alignment issue is fixed. Here are some views from the different phones and tablets.
Screenshot (288)
Screenshot (293)
Screenshot (294)

**Comment by BreadGenie** [comment]
@Ayshhh thanks for the contribution!

**Pull request merged**
